#!/usr/bin/env python

'''
The world_model node exposes the worldlib API over ROS topics and services.

@author:  Russell Toris
@version: January 23, 2013
'''

import rospy
from worldlib import world_object_instance_database
from world_msgs.srv import *
from world_msgs.msg import WorldObjectInstance
from rosbridge_library.internal.message_conversion import extract_values, populate_instance

# the connection to the database
woid = world_object_instance_database.WorldObjectInstanceDatabase()

def create_world_object_instance(request):
    '''
    The create_world_object_instance service call will create a new instance in the world object 
    instance database. A unique instance_id will be assigned and the creation time will be created.
    
    @param request: the service request
    @type  request: CreateWorldObjectInstance
    @return: the service response
    @rtype:  CreateWorldObjectInstanceResponse
    '''
    # update the times
    t = rospy.get_rostime()
    request.instance.creation = t
    request.instance.update = t
    # convert to JSON and insert
    instance_id = woid.insert(extract_values(request.instance))
    return CreateWorldObjectInstanceResponse(instance_id)

def update_world_object_instance(request):
    '''
    The update_world_object_instance service call will update an instance in the world object 
    instance database. The update time will be set to the current time.
    
    @param request: the service request
    @type  request: UpdateWorldObjectInstance
    @return: the service response
    @rtype:  UpdateWorldObjectInstanceResponse
    '''
    # update the update time
    request.instance.update = rospy.get_rostime()
    # convert to JSON and update
    success = woid.update_entity_by_instance_id(request.instance_id, extract_values(request.instance))
    if(success is not True):
        rospy.logwarn(request.instance_id + ' could not be updated.')

    return UpdateWorldObjectInstanceResponse(success)

def search_world_object_instance_tags(request):
    '''
    Search for and return all instances in the database that have the given list of tags.
    
    @param request: the service request
    @type  request: WorldObjectInstanceTagSearch
    @return: the service response
    @rtype:  WorldObjectInstanceTagSearchResponse
    '''
    # convert into ROS messages
    entities = woid.search_tags(request.tags)
    instances = []
    for e in entities:
        del e['_id']
        instances.append(populate_instance(e, WorldObjectInstance()))
    return WorldObjectInstanceTagSearchResponse(instances)

def main():
    '''
    The main run function for the world_model node.
    '''
    rospy.init_node('world_model')
    # advertise the services
    rospy.Service('~create_world_object_instance', CreateWorldObjectInstance, 
                  create_world_object_instance)
    rospy.Service('~search_world_object_instance_tags', WorldObjectInstanceTagSearch, 
                  search_world_object_instance_tags)
    rospy.Service('~update_world_object_instance', UpdateWorldObjectInstance, 
                  update_world_object_instance)
    rospy.loginfo('World Model Node is Ready')
    rospy.spin()

if __name__ == '__main__':
    main()
